import "./globals.css";
import localFont from "next/font/local";
import { Navbar } from "./components/Navbar/Navbar";
import { ThemeProvider } from "./components/Buttons/ThemeContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// const Raleway = localFont({
//   src: [
//     {
//       path: "./assets/Raleway-Medium.ttf",
//       weight: "500",
//       style: "medium",
//     },
//     {
//       path: "./assets/Raleway-Bold.ttf",
//       weight: "700",
//       style: "bold",
//     },
//     {
//       path: "./assets/Raleway-Black.ttf",
//       weight: "900",
//       style: "black",
//     },
//   ],
// });

const FiraCode = localFont({
  src: [
    {
      path: "./assets/font/FiraCode-Regular.ttf",
      weight: "400",
      style: "Regular",
    },
    {
      path: "./assets/font/FiraCode-Medium.ttf",
      weight: "500",
      style: "Medium",
    },
    {
      path: "./assets/font/FiraCode-Bold.ttf",
      weight: "700",
      style: "Bold",
    },
  ],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ThemeProvider>
      <html id="html" lang="en" className={`${FiraCode.className} `}>
        <body className="dark:bg-slate-900 overflow-x-hidden">
          <Navbar />
          <div className=" relative mx-auto mt-16  md:mt-0 md:container lg:px-32 xl:px-72 max-h-screen">
            {children}
          </div>
        </body>
      </html>
    </ThemeProvider>
  );
}
